### ISSUE TITLE
Implement Souden et al (2011) multichannel MCRA

### ISSUE THREAD

**Issue by mim** [speechLabBcCuny/messlJsalt15#11]
Implement the algorithm(s) from [this paper](http://externe.emt.inrs.ca/users/benesty/papers/aslp_sep2011.pdf)

Souden, M., Chen, J., Benesty, J., & Affes, S. (2011). An integrated solution for online multichannel noise tracking and reduction. IEEE Transactions on Audio, Speech, and Language Processing, 19(7), 2159-2169.

**Comment by tvanh512** [comment]
messlJsalt15/wrapper_Souden_multi.m 
messlJsalt15/noise_covariance_Souden_multi.m

**Comment by mim** [comment]
Will noise_covariance_Souden_multi work inside of the standard enhance_wrapper.m instead of your custom wrapper_Souden_multi?  If not, please make it do so.  If you want, you can add a script that calls enhance_wrapper with the proper arguments to run your code.  Also, change the name of noise_covariance_Souden_multi.m to stubI_souden11.m.

**Comment by tvanh512** [comment]
I upload on Master branch. It can with standard enhance_wrapper. However, notice that the inFilesOrPattern is '.*\.CH1\.wav$' and filePerChan = 1.  example: enhance_wrapper(@(X,fail,fs,file) stubI_souden11(X,fail,fs,file,5,6),'/Users/VietAnh/Documents/chime3/test','/Users/VietAnh/Documents/Courses/Speech/Classproject/Project_final/abc',[1 1],0,0,1, '.*\.CH1\.wav$')

**Comment by mim** [comment]
Done by Viet Anh in 102a514863a9c941570551e7f13d068e5883c2d1
