### ISSUE TITLE
Evauate performance using PESQ instead of PEASS

### ISSUE THREAD

**Issue by mim** [speechLabBcCuny/messlJsalt15#16]
PESQ only requires clean reference (for dt and et data, use output of supervised MVDR).  Also requires estimated clean speech, use output of MESSL-MVDR, etc.  For noisy baseline, use channel 5 as "estimated" clean speech.

**Comment by nateanl** [comment]
In order to use pesq, I need to install Image Processing Toolbox.  How can I install this toolbox in command line?

The message in the matlab:
`To use 'dctmtx', the following product must be both licensed and installed:
  Image Processing Toolbox

Error in pesq_psychoacoustic_model (line 159)
    D = dctmtx(Nb);

Error in pesq (line 122)
pesq_mos= pesq_psychoacoustic_model (ref_data, ref_Nsamples, deg_data, ...`

**Comment by mim** [comment]
You should be able to use this:
  https://sourceforge.net/p/octave/signal/ci/default/tree/inst/dctmtx.m

**Comment by nateanl** [comment]
Okay, thank you.
Another problem is when I try to use the pesq function like this:
`pval = pesq(file_a,file_b)`

It shows this message:
```
Not enough input arguments.

Error in pesq (line 123)
    deg_Nsamples, dctSmooth );
```

Did you try to use pesq before? I think I need to define dctSmooth by myself...

**Comment by mim** [comment]
I wrote a little wrapper script around this pesq function that resamples signals to the sampling rate pesq expects (I think 8000 Hz), writes them to temporary files, and calls pesq on them.  Unfortunately, I can't find this script now.  I think that it used dctSmooth = inf, but we could try different values and see which one makes the most sense.

**Comment by nateanl** [comment]
The result for dt05_simu: [sredsheet](https://docs.google.com/spreadsheets/d/1AcVEtE-5fXNrQzBZ8oMt8jj9MdW5IV4jkgOrG1fuOKU/edit#gid=1120253641)
What do you think of the result? Is it good or not?

**Comment by mim** [comment]
Looks ok, but it's hard to tell without having the PESQ of the noisy speech (channel 5) to compare against.

**Comment by nateanl** [comment]
That's true, I will get all the results soon.

**Comment by nateanl** [comment]
According to the result, the average version of combining the masks gets the best result.

**Comment by mim** [comment]
Done by Zhaoheng.
