### ISSUE TITLE
Compare to baseline Souden et al 2011 algorithm

### ISSUE THREAD

**Issue by mim** [speechLabBcCuny/messlJsalt15#17]
Anh has processed files with `stubI_souden11` and put them in `/scratch/vietanh/chime3/souden11/`.  We just need to analyze their performance using PESQ and ASR.  It is his implementation of the algorithm described in this paper:

> [1]Souden, M., Chen, J., Benesty, J., & Affes, S. (2011).
>  An integrated solution for online multichannel noise tracking and reduction.
> IEEE Transactions on Audio, Speech, and Language Processing, 19(7), 2159-2169.

**Comment by nateanl** [comment]
Got it.

**Comment by mim** [comment]
So that second row of results is the average of the MESSL output mask and the LSTM mask for combination 3, where the LSTM mask is combined with the MESSL mask during iterations?

**Comment by nateanl** [comment]
They are combination3, with maskhold = 11 or 20
