### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by nateanl** [speechLabBcCuny/messlJsalt15#18]
In `data/chime3/lstmc2Avg/et05_real_lstmc2Avg/log` directory, the information in the log file shows:

`/var/spool/gridengine/execd/localhost/job_scripts/45: line 11: compute-mfcc-feats: command not found`
`copy-feats: error while loading shared libraries: libfst.so.1: cannot open shared object file: No such file or directory`

How did you install openfst in your directory and link it with the kaldi?

**Comment by mim** [comment]
It looks like that might be a problem with your search path, because it says it can't find `compute-mfcc-feats`. Either that or the executable permission was removed from it. I'm not sure about the other errors though. You can always try recompiling everything by following the instructions in kaldi's root directory.

**Comment by nateanl** [comment]
I make it to work by cloning kaldi from GitHub and copy the j-salt to egs. 
Here I got another error:
`queue.pl: Error submitting jobs to queue (return status was 256)
queue log file is exp/mdm8/tri4a/decode_chime3_lm_tgpr_5k_et05_real_lstmc4Avg.si/q/decode.log, command was qsub -v PATH -cwd -S /bin/bash -j y -l arch=*64* -o exp/mdm8/tri4a/decode_chime3_lm_tgpr_5k_et05_real_lstmc4Avg.si/q/decode.log -l arch=*64* -l mem_free=4G,ram_free=4G -pe smp 3   -t 1:4 /scratch/near/asr/kaldi/egs/jsalt15-ffs/s5/exp/mdm8/tri4a/decode_chime3_lm_tgpr_5k_et05_real_lstmc4Avg.si/q/decode.sh >>exp/mdm8/tri4a/decode_chime3_lm_tgpr_5k_et05_real_lstmc4Avg.si/q/decode.log 2>&1
Output of qsub was: Unable to run job: unknown resource "ram_free".`

The related website: [kaldi](https://sourceforge.net/p/kaldi/discussion/1355348/thread/7ca6e68d/)

Shall we install something on SGE, or is there a way I can change the shell and remove the ram_free?

**Comment by mim** [comment]
Try copying this file into your `s5` directory: `/home/mim/code/asr/kaldi/egs/ami/s5b/cmd.sh` to overwrite the `cmd.sh` that is there.  This goes around SGE to run things directly.  Since it's all running on crescent anyway, this will avoid some headaches.

**Comment by nateanl** [comment]
I call it magic.
