### ISSUE TITLE
Reproduce results from mandel & barker, 2016

### ISSUE THREAD

**Issue by mim** [speechLabBcCuny/messlJsalt15#20]
Use replayMessl based on messl masks in `/scratch/mim/chime3/messlMcMvdrMrf.2Hard5Lbp4Slate/` to reproduce the best performing outputs from Mandel & Barker, Interspeech 2016, which are in `/scratch/mim/chime3/replaySlateXcMaskSoudenMaxSup09db`

They achieve WER of 19.7 on the dev set (and 32.6 on the test set) using the AMI recognizer.

**Comment by nateanl** [comment]
The WER generated from step1, I got 20.42 on the dev set and 36.4 on the test set.

The WER from step 2, I got 21.97 on the dev set and 34.37 on the test set.

**Comment by mim** [comment]
Step 1 and step 2 of what? What is the difference? Does this mean you were able to reproduce the results or not?

**Comment by nateanl** [comment]
Sorry, step one means extracting the mask and apply it onto the beamformed audio. Step two means using the mask from step 1 and use replayMessl to get the enhanced audio.

I was not able to get the same WER score. As you said in theory the result should be the same with the one in the paper. So there should be something different in the code.

**Comment by mim** [comment]
So what stub are you using for step 1?  Can you compare some of the wav files (or data files) between these different systems and see if you can figure out what's different?

**Comment by nateanl** [comment]
The audio files of LSTM model are in `/scratch/near/CHiME3/fixed_model/v2/lstm/wav`, you can listen to them.

**Comment by nateanl** [comment]
Results here: [spreadsheet](https://docs.google.com/spreadsheets/d/1IunWYy3mEmxnLaxAGZv7mchx3Nm7pxhBnW-VUUbZSwM/edit#gid=558370190)
Comparing different combination options of LSTM mask and MESSL mask, the messl mask only got the best result, LSTM only got the worst. Max of LSTM and MESSL is better than average and min.

**Comment by mim** [comment]
Done. Needed to not pass in 'ipd' argument to main messl script.
